application:
  base_url: "http://127.0.0.1"
  port: 8000
  host: 0.0.0.0
  hmac_secret: "a-secret-so-long-you-cant-keep-it-hbnhknhhxbhkbfhbfhbhk bxzcccccccchcb hbhchkxchkbhxc"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000